### PR TITLE
Style and content changes

### PR DESCRIPTION
**Pull request by SteveBarnett**

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@avermeulen 👓 , please!

**Comment by avermeulen** [comment]
@SteveBarnett I added a few links and clarified the search bar should search automatically. If it looks fine for you please merge. After that I will add technical details about the search process.

**Comment by avermeulen** [comment]
@SteveBarnett this is not using the styles for your new fancy links warnings. It's using wrong style sheet I suppose?

**Comment by SteveBarnett** [comment]
@avermeulen Updated the header to use the shared stylings.

**Comment by SteveBarnett** [comment]
@avermeulen ping! Happy?

**Pull request merged**
